export const APPOINTMENT_ADD_REQUEST = "APPOINTMENT_ADD_REQUEST";
export const APPOINTMENT_ADD_SUCCESS = "APPOINTMENT_ADD_SUCCESS";
export const APPOINTMENT_ADD_FAIL = "APPOINTMENT_ADD_FAIL";
export const APPOINTMENT_ADD_RESET = "APPOINTMENT_ADD_RESET";

export const APPOINTMENT_GET_REQUEST = "APPOINTMENT_GET_REQUEST";
export const APPOINTMENT_GET_SUCCESS = "APPOINTMENT_GET_SUCCESS";
export const APPOINTMENT_GET_FAIL = "APPOINTMENT_GET_FAIL";

export const ORDER_GET_REQUEST = "ORDER_GET_REQUEST";
export const ORDER_GET_SUCCESS = "ORDER_GET_SUCCESS";
export const ORDER_GET_FAIL = "ORDER_GET_FAIL";

export const ALL_SALES_GET_REQUEST = "ALL_SALES_GET_REQUEST";
export const ALL_SALES_GET_SUCCESS = "ALL_SALES_GET_SUCCESS";
export const ALL_SALES_GET_FAIL = "ALL_SALES_GET_FAIL";
