export const APPOINTMENT_GRAPH_REQUEST = "APPOINTMENT_GRAPH_REQUEST";
export const APPOINTMENT_GRAPH_SUCCESS = "APPOINTMENT_GRAPH_SUCCESS";
export const APPOINTMENT_GRAPH_FAILURE = "APPOINTMENT_GRAPH_FAILURE";
