export const BRANCHES_LIST_GET_REQUEST = "BRANCHES_LIST_GET_REQUEST";
export const BRANCHES_LIST_GET_SUCCESS = "BRANCHES_LIST_GET_SUCCESS";
export const BRANCHES_LIST_GET_FAIL = "BRANCHES_LIST_GET_FAIL";

export const BRANCH_ACTIVE_GET_REQUEST = "BRANCH_ACTIVE_GET_REQUEST";
export const BRANCH_ACTIVE_GET_SUCCESS = "BRANCH_ACTIVE_GET_SUCCESS";
export const BRANCH_ACTIVE_GET_FAIL = "BRANCH_ACTIVE_GET_FAIL";

export const BRANCH_CREATE_REQUEST = "BRANCH_CREATE_REQUEST";
export const BRANCH_CREATE_SUCCESS = "BRANCH_CREATE_SUCCESS";
export const BRANCH_CREATE_FAIL = "BRANCH_CREATE_FAIL";
export const BRANCH_CREATE_RESET = "BRANCH_CREATE_RESET";

export const BRANCHES_ACL_GET_REQUEST = "BRANCHES_ACL_GET_REQUEST";
export const BRANCHES_ACL_GET_SUCCESS = "BRANCHES_ACL_GET_SUCCESS";
export const BRANCHES_ACL_GET_FAIL = "BRANCHES_ACL_GET_FAIL";

export const BRANCH_IMAGE_REQUEST = "BRANCH_IMAGE_REQUEST";
export const BRANCH_IMAGE_SUCCESS = "BRANCH_IMAGE_SUCCESS";
export const BRANCH_IMAGE_FAIL = "BRANCH_IMAGE_FAIL";
export const BRANCH_IMAGE_RESET = "BRANCH_IMAGE_RESET";
