export const BRAND_ADD_REQUEST = "BRAND_ADD_REQUEST";
export const BRAND_ADD_SUCCESS = "BRAND_ADD_SUCCESS";
export const BRAND_ADD_FAIL = "BRAND_ADD_FAIL";
export const BRAND_ADD_RESET = "BRAND_ADD_RESET";

export const BRAND_GET_REQUEST = "BRAND_GET_REQUEST";
export const BRAND_GET_SUCCESS = "BRAND_GET_SUCCESS";
export const BRAND_GET_FAIL = "BRAND_GET_FAIL";

export const BRAND_UPDATE_REQUEST = "BRAND_UPDATE_REQUEST";
export const BRAND_UPDATE_SUCCESS = "BRAND_UPDATE_SUCCESS";
export const BRAND_UPDATE_FAIL = "BRAND_UPDATE_FAIL";
export const BRAND_UPDATE_RESET = "BRAND_UPDATE_RESET";
