export const CLIENTS_ADD_REQUEST = "CLIENTS_ADD_REQUEST";
export const CLIENTS_ADD_SUCCESS = "CLIENTS_ADD_SUCCESS";
export const CLIENTS_ADD_FAIL = "CLIENTS_ADD_FAIL";
export const CLIENTS_ADD_RESET = "CLIENTS_ADD_RESET";

export const CLIENTS_GET_REQUEST = "CLIENTS_GET_REQUEST";
export const CLIENTS_GET_SUCCESS = "CLIENTS_GET_SUCCESS";
export const CLIENTS_GET_FAIL = "CLIENTS_GET_FAIL";

export const CLIENTS_UPDATE_REQUEST = "CLIENTS_UPDATE_REQUEST";
export const CLIENTS_UPDATE_SUCCESS = "CLIENTS_UPDATE_SUCCESS";
export const CLIENTS_UPDATE_FAIL = "CLIENTS_UPDATE_FAIL";
export const CLIENTS_UPDATE_RESET = "CLIENTS_UPDATE_RESET";

export const CLIENTS_TOGGLE_REQUEST = "CLIENTS_TOGGLE_REQUEST";
export const CLIENTS_TOGGLE_SUCCESS = "CLIENTS_TOGGLE_SUCCESS";
export const CLIENTS_TOGGLE_FAIL = "CLIENTS_TOGGLE_FAIL";

export const CLIENTS_SEARCH_REQUEST = "CLIENTS_SEARCH_REQUEST";
export const CLIENTS_SEARCH_SUCCESS = "CLIENTS_SEARCH_SUCCESS";
export const CLIENTS_SEARCH_FAIL = "CLIENTS_SEARCH_FAIL";
