export const PRODCATEGORY_ADD_REQUEST = "PRODCATEGORY_ADD_REQUEST";
export const PRODCATEGORY_ADD_SUCCESS = "PRODCATEGORY_ADD_SUCCESS";
export const PRODCATEGORY_ADD_FAIL = "PRODCATEGORY_ADD_FAIL";
export const PRODCATEGORY_ADD_RESET = "PRODCATEGORY_ADD_RESET";

export const PRODCATEGORY_GET_REQUEST = "PRODCATEGORY_GET_REQUEST";
export const PRODCATEGORY_GET_SUCCESS = "PRODCATEGORY_GET_SUCCESS";
export const PRODCATEGORY_GET_FAIL = "PRODCATEGORY_GET_FAIL";
export const PRODCATEGORY_GET_RESET = "PRODCATEGORY_GET_RESET";

export const PRODCATEGORY_UPDATE_REQUEST = "PRODCATEGORY_UPDATE_REQUEST";
export const PRODCATEGORY_UPDATE_SUCCESS = "PRODCATEGORY_UPDATE_SUCCESS";
export const PRODCATEGORY_UPDATE_FAIL = "PRODCATEGORY_UPDATE_FAIL";
export const PRODCATEGORY_UPDATE_RESET = "PRODCATEGORY_UPDATE_RESET";
