export const SALES_DATA_REQUEST = "SALES_DATA_REQUEST";
export const SALES_DATA_SUCCESS = "SALES_DATA_SUCCESS";
export const SALES_DATA_FAIL = "SALES_DATA_FAIL";

export const SALES_HISTORY_REQUEST = "SALES_HISTORY_REQUEST";
export const SALES_HISTORY_SUCCESS = "SALES_HISTORY_SUCCESS";
export const SALES_HISTORY_FAIL = "SALES_HISTORY_FAIL";

export const APPOINTMENT_HISTORY_REQUEST = "APPOINTMENT_HISTORY_REQUEST";
export const APPOINTMENT_HISTORY_SUCCESS = "APPOINTMENT_HISTORY_SUCCESS";
export const APPOINTMENT_HISTORY_FAIL = "APPOINTMENT_HISTORY_FAIL";
