export const SERVICES_ADD_REQUEST = "SERVICES_ADD_REQUEST";
export const SERVICES_ADD_SUCCESS = "SERVICES_ADD_SUCCESS";
export const SERVICES_ADD_FAIL = "SERVICES_ADD_FAIL";
export const SERVICES_RESET = "SERVICES_RESET";

export const SERVICES_GET_REQUEST = "SERVICES_GET_REQUEST";
export const SERVICES_GET_SUCCESS = "SERVICES_GET_SUCCESS";
export const SERVICES_GET_FAIL = "SERVICES_GET_FAIL";

export const SERVICES_SEARCH_REQUEST = "SERVICES_SEARCH_REQUEST";
export const SERVICES_SEARCH_SUCCESS = "SERVICES_SEARCH_SUCCESS";
export const SERVICES_SEARCH_FAIL = "SERVICES_SEARCH_FAIL";

export const SERVICES_UPDATE_REQUEST = "SERVICES_UPDATE_REQUEST";
export const SERVICES_UPDATE_SUCCESS = "SERVICES_UPDATE_SUCCESS";
export const SERVICES_UPDATE_FAIL = "SERVICES_UPDATE_FAIL";
export const SERVICES_UPDATE_RESET = "SERVICES_UPDATE_RESET";

export const SERVICES_TOGGLE_REQUEST = "SERVICES_TOGGLE_REQUEST";
export const SERVICES_TOGGLE_SUCCESS = "SERVICES_TOGGLE_SUCCESS";
export const SERVICES_TOGGLE_FAIL = "SERVICES_TOGGLE_FAIL";

export const TOP_SERVICES_REQUEST = "TOP_SERVICES_REQUEST";
export const TOP_SERVICES_SUCCESS = "TOP_SERVICES_SUCCESS";
export const TOP_SERVICES_FAIL = "TOP_SERVICES_FAIL";
