export const STAFF_ADD_REQUEST = "STAFF_ADD_REQUEST";
export const STAFF_ADD_SUCCESS = "STAFF_ADD_SUCCESS";
export const STAFF_ADD_FAIL = "STAFF_ADD_FAIL";
export const STAFF_ADD_RESET = "STAFF_ADD_RESET";

export const STAFF_GET_REQUEST = "STAFF_GET_REQUEST";
export const STAFF_GET_SUCCESS = "STAFF_GET_SUCCESS";
export const STAFF_GET_FAIL = "STAFF_GET_FAIL";

export const STAFF_WORK_REQUEST = "STAFF_WORK_REQUEST";
export const STAFF_WORK_SUCCESS = "STAFF_WORK_SUCCESS";
export const STAFF_WORK_FAIL = "STAFF_WORK_FAIL";
export const STAFF_WORK_RESET = "STAFF_WORK_RESET";

export const STAFF_UPDATE_REQUEST = "STAFF_UPDATE_REQUEST";
export const STAFF_UPDATE_SUCCESS = "STAFF_UPDATE_SUCCESS";
export const STAFF_UPDATE_FAIL = "STAFF_UPDATE_FAIL";
export const STAFF_UPDATE_RESET = "STAFF_UPDATE_RESET";

export const STAFF_TOGGLE_REQUEST = "STAFF_TOGGLE_REQUEST";
export const STAFF_TOGGLE_SUCCESS = "STAFF_TOGGLE_SUCCESS";
export const STAFF_TOGGLE_FAIL = "STAFF_TOGGLE_FAIL";

export const STAFF_SEARCH_REQUEST = "STAFF_SEARCH_REQUEST";
export const STAFF_SEARCH_SUCCESS = "STAFF_SEARCH_SUCCESS";
export const STAFF_SEARCH_FAIL = "STAFF_SEARCH_FAIL";

export const STAFF_HOURS_REQUEST = "STAFF_HOURS_REQUEST";
export const STAFF_HOURS_SUCCESS = "STAFF_HOURS_SUCCESS";
export const STAFF_HOURS_FAIL = "STAFF_HOURS_FAIL";
export const STAFF_HOURS_RESET = "STAFF_HOURS_RESET";

export const STAFF_IMAGE_REQUEST = "STAFF_IMAGE_REQUEST";
export const STAFF_IMAGE_SUCCESS = "STAFF_IMAGE_SUCCESS";
export const STAFF_IMAGE_FAIL = "STAFF_IMAGE_FAIL";

export const TOP_STAFF_REQUEST = "TOP_STAFF_REQUEST";
export const TOP_STAFF_SUCCESS = "TOP_STAFF_SUCCESS";
export const TOP_STAFF_FAIL = "TOP_STAFF_FAIL";
