export const STOCK_ORDERS_ADD_REQUEST = "STOCK_ORDERS_ADD_REQUEST";
export const STOCK_ORDERS_ADD_SUCCESS = "STOCK_ORDERS_ADD_SUCCESS";
export const STOCK_ORDERS_ADD_FAIL = "STOCK_ORDERS_ADD_FAIL";
export const STOCK_ORDERS_ADD_RESET = "STOCK_ORDERS_ADD_RESET";

export const STOCK_ORDERS_GET_REQUEST = "STOCK_ORDERS_GET_REQUEST";
export const STOCK_ORDERS_GET_SUCCESS = "STOCK_ORDERS_GET_SUCCESS";
export const STOCK_ORDERS_GET_FAIL = "STOCK_ORDERS_GET_FAIL";
export const STOCK_ORDERS_GET_RESET = "STOCK_ORDERS_GET_RESET";

export const STOCK_ORDERS_UPDATE_REQUEST = "STOCK_ORDERS_UPDATE_REQUEST";
export const STOCK_ORDERS_UPDATE_SUCCESS = "STOCK_ORDERS_UPDATE_SUCCESS";
export const STOCK_ORDERS_UPDATE_FAIL = "STOCK_ORDERS_UPDATE_FAIL";
export const STOCK_ORDERS_UPDATE_RESET = "STOCK_ORDERS_UPDATE_RESET";
