export const SUBSCRIPTION_ADD_REQUEST = "SUBSCRIPTION_ADD_REQUEST";
export const SUBSCRIPTION_ADD_SUCCESS = "SUBSCRIPTION_ADD_SUCCESS";
export const SUBSCRIPTION_ADD_FAIL = "SUBSCRIPTION_ADD_FAIL";
export const SUBSCRIPTION_ADD_RESET = "SUBSCRIPTION_ADD_RESET";

export const SUBSCRIPTION_GET_REQUEST = "SUBSCRIPTION_GET_REQUEST";
export const SUBSCRIPTION_GET_SUCCESS = "SUBSCRIPTION_GET_SUCCESS";
export const SUBSCRIPTION_GET_FAIL = "SUBSCRIPTION_GET_FAIL";

export const SUBSCRIPTION_UPDATE_REQUEST = "SUBSCRIPTION_UPDATE_REQUEST";
export const SUBSCRIPTION_UPDATE_SUCCESS = "SUBSCRIPTION_UPDATE_SUCCESS";
export const SUBSCRIPTION_UPDATE_FAIL = "SUBSCRIPTION_UPDATE_FAIL";
export const SUBSCRIPTION_UPDATE_RESET = "SUBSCRIPTION_UPDATE_RESET";

export const SUBSCRIPTION_TOGGLE_REQUEST = "SUBSCRIPTION_TOGGLE_REQUEST";
export const SUBSCRIPTION_TOGGLE_SUCCESS = "SUBSCRIPTION_TOGGLE_SUCCESS";
export const SUBSCRIPTION_TOGGLE_FAIL = "SUBSCRIPTION_TOGGLE_FAIL";
export const SUBSCRIPTION_TOGGLE_RESET = "SUBSCRIPTION_TOGGLE_RESET";

export const SUBSCRIPTION_SEARCH_REQUEST = "SUBSCRIPTION_SEARCH_REQUEST";
export const SUBSCRIPTION_SEARCH_SUCCESS = "SUBSCRIPTION_SEARCH_SUCCESS";
export const SUBSCRIPTION_SEARCH_FAIL = "SUBSCRIPTION_SEARCH_FAIL";

export const SALON_SUBSCRIPTION_ADD_REQUEST = "SALON_SUBSCRIPTION_ADD_REQUEST";
export const SALON_SUBSCRIPTION_ADD_SUCCESS = "SALON_SUBSCRIPTION_ADD_SUCCESS";
export const SALON_SUBSCRIPTION_ADD_FAIL = "SALON_SUBSCRIPTION_ADD_FAIL";
export const SALON_SUBSCRIPTION_ADD_RESET = "SALON_SUBSCRIPTION_ADD_RESET";

export const SALON_SUBSCRIPTION_GET_REQUEST = "SALON_SUBSCRIPTION_GET_REQUEST";
export const SALON_SUBSCRIPTION_GET_SUCCESS = "SALON_SUBSCRIPTION_GET_SUCCESS";
export const SALON_SUBSCRIPTION_GET_FAIL = "SALON_SUBSCRIPTION_GET_FAIL";
