export const SUPPLIER_ADD_REQUEST = "SUPPLIER_ADD_REQUEST";
export const SUPPLIER_ADD_SUCCESS = "SUPPLIER_ADD_SUCCESS";
export const SUPPLIER_ADD_FAIL = "SUPPLIER_ADD_FAIL";
export const SUPPLIER_ADD_RESET = "SUPPLIER_ADD_RESET";

export const SUPPLIER_GET_REQUEST = "SUPPLIER_GET_REQUEST";
export const SUPPLIER_GET_SUCCESS = "SUPPLIER_GET_SUCCESS";
export const SUPPLIER_GET_FAIL = "SUPPLIER_GET_FAIL";
export const SUPPLIER_GET_RESET = "SUPPLIER_GET_RESET";

export const SUPPLIER_UPDATE_REQUEST = "SUPPLIER_UPDATE_REQUEST";
export const SUPPLIER_UPDATE_SUCCESS = "SUPPLIER_UPDATE_SUCCESS";
export const SUPPLIER_UPDATE_FAIL = "SUPPLIER_UPDATE_FAIL";
export const SUPPLIER_UPDATE_RESET = "SUPPLIER_UPDATE_RESET";
